# Generated by Django 5.0 on 2025-11-14 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_profile_image_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('customer_created', 'New Customer'), ('order_placed', 'Order Placed'), ('order_delivered', 'Order Delivered'), ('cart_abandoned', 'Cart Abandoned'), ('customer_inactive', 'Customer Inactive'), ('ticket_created', 'Support Ticket Created'), ('feedback_received', 'Feedback Received'), ('custom', 'Custom Trigger')], max_length=50)),
                ('trigger_conditions', models.JSONField(default=dict, help_text='Additional conditions for trigger')),
                ('action_type', models.CharField(choices=[('send_email', 'Send Email'), ('send_sms', 'Send SMS'), ('create_task', 'Create Task'), ('assign_to_user', 'Assign to User'), ('update_customer_status', 'Update Customer Status'), ('add_to_segment', 'Add to Segment'), ('award_points', 'Award Loyalty Points')], max_length=50)),
                ('action_config', models.JSONField(default=dict, help_text='Configuration for the action')),
                ('is_active', models.BooleanField(default=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('criteria', models.JSONField(default=dict, help_text='JSON criteria for segment membership')),
                ('is_dynamic', models.BooleanField(default=True, help_text='Auto-update based on criteria')),
                ('customer_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CartAbandonment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_data', models.JSONField(default=dict, help_text='Stored cart items')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abandoned_at', models.DateTimeField(auto_now_add=True)),
                ('recovered', models.BooleanField(default=False)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abandoned_carts', to='crm.customer')),
            ],
            options={
                'ordering': ['-abandoned_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('phone_enabled', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=False)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('preferred_contact_time', models.CharField(blank=True, max_length=50)),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('gdpr_consent_date', models.DateTimeField(blank=True, null=True)),
                ('data_processing_consent', models.BooleanField(default=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comm_preferences', to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifetime_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_frequency', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('days_since_last_purchase', models.IntegerField(default=0)),
                ('churn_probability', models.DecimalField(decimal_places=2, default=0, help_text='0-100 percentage', max_digits=5)),
                ('predicted_next_purchase_date', models.DateField(blank=True, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRFM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recency_score', models.IntegerField(default=0, help_text='1-5 score')),
                ('frequency_score', models.IntegerField(default=0, help_text='1-5 score')),
                ('monetary_score', models.IntegerField(default=0, help_text='1-5 score')),
                ('rfm_segment', models.CharField(blank=True, help_text='e.g., Champions, Loyal, At Risk', max_length=50)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfm_score', to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('points_balance', models.IntegerField(default=0)),
                ('lifetime_points', models.IntegerField(default=0)),
                ('total_redeemed', models.IntegerField(default=0)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Points Earned'), ('redeemed', 'Points Redeemed'), ('expired', 'Points Expired'), ('adjusted', 'Manual Adjustment')], max_length=20)),
                ('points', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loyalty_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='crm.loyaltyprogram')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('social', 'Social Media'), ('multi', 'Multi-Channel')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.IntegerField(default=0)),
                ('opened_count', models.IntegerField(default=0)),
                ('clicked_count', models.IntegerField(default=0)),
                ('conversion_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customersegment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_customer', 'Waiting for Customer'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('chat', 'Live Chat'), ('social', 'Social Media'), ('in_store', 'In-Store'), ('web', 'Website')], default='web', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('first_response_time', models.DateTimeField(blank=True, null=True)),
                ('resolution_time', models.DateTimeField(blank=True, null=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='crm.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('nps', 'Net Promoter Score'), ('csat', 'Customer Satisfaction'), ('ces', 'Customer Effort Score'), ('review', 'Product Review'), ('general', 'General Feedback')], max_length=20)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True)),
                ('comment', models.TextField(blank=True)),
                ('sentiment', models.CharField(blank=True, help_text='Auto-detected: positive, negative, neutral', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Show in public reviews')),
                ('responded', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='crm.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.product')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.supportticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note (not visible to customer)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
